<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="NBuilder" Version="6.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.8" />
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
    <PackageReference Include="RT.Comb" Version="4.0.3" />
	<PackageReference Include="OpenTelemetry" Version="1.12.0" />
	<PackageReference Include="OpenTelemetry.Exporter.Jaeger" Version="1.5.1" />
	<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.12.0" />
	<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.12.0" />
	<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.12.0" />
	<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.12.0" />
	<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.12.0" />
	<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.12.0" />
    
  </ItemGroup>

</Project>
